### ISSUE TITLE
Why is my return type violation unchecked?

### ISSUE THREAD

**Issue by janwirth** [fluture-js/fluture-sanctuary-types#70]
Hey there

I am wondering why my Fluture return value is not throwing for `executeWrite` but only as soon as we get to `executeRead`. How can I make it throw earlier?
```
TypeError: Invalid value

executeRead :: { path :: String } -> Future Any Buffer
                         ^^^^^^
                           1
```

My implementation:
```js

const executeWrite_ = F.encaseP(({ path, contents }) =>
    fs.promises.writeFile(path, contents).then(() => 12) // PROVOKE TYPE VIOLATION
);

const executeWrite = def("executeWrite")({})([
    WriteOperationType,
    FlutureTypes.FutureType($.Any)($.String)
])(executeWrite_);

const executeRead_ = F.encaseP(({ path }) => fs.promises.readFile(path));
```

The test which writes a file and reads back from it.
```js
test("write file e2e", t =>
    new Promise((resolve, reject) => {
        const fileName = "testFile";
        const contents =
            "contents " +
            Array.from({ length: 1 }, () => Math.random().toString(36)[2]).join(
                ""
            );
        const writeOp = executeWrite({ path: fileName, contents });
        const readOp = path => executeRead({ path });
        const readWrite = F.chain(readOp)(F.map(log("written"))(writeOp));
        const e2e = F.map(toString)(readWrite);
        F.fork(someError => reject(someError))(readContents => {
            log("resolve")(contents);
            t.equals(readContents, contents);
            resolve();
        })(e2e);
    }));
```

Thanks for the help 👋

**Comment by Avaq** [comment]
Fluture can only provide the Sanctuary type checker with its inner value if the inner value is synchronously available. Most Futures are lazily evaluated, which means Sanctuary's type checker will be running before the inner value is known to the Future.

The extraction of the inner value is based on Fluture's [`extractLeft` and `extractRight`](https://github.com/fluture-js/Fluture#extractLeft) functions. It works on Futures whose values are known beforehand (such as those created by `resolve`, `after`, etc.), and on Futures whose resolution values are kept in memory (such as those created by `cache`). It's sadly the best we can do.
